# Generated by Django 5.1.2 on 2024-11-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapper_live', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
